config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "stories#index" 
  resources :stories do
  	resources :comments
  	resources :votes
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :story



end

app/models/story.rb
class Story < ActiveRecord::Base
	# template for building story instances
	validates_format_of :url, with: URI.regexp

	validates :url, presence: true, uniqueness: true

	validates :title, presence: true, uniqueness: true

	validates :description, length: { maximum: 150, minimum: 20 }

	has_many :comments
	has_many :votes

	

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	# counter_cache keeps count of how many there are
	belongs_to :story, counter_cache: true
	# scope story makes the validation specific to the story
	validates :ip_address, uniqueness: { scope: :story } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :find_story, only: [:new, :create]

  def new
    # keeping code DRY
    # @story = Story.find(params[:story_id])

  	@comment = @story.comments.new

  end

  def create
  	# keeping code DRY
    # @story = Story.find(params[:story_id])

  	@comment = @story.comments.new(comment_params)
  	@comment.save
  	redirect_to story_path(@story)

  end

  def destroy
  	@comment= Comment.find(params[:id])
  	@comment.destroy
  	redirect_to story_path(@comment.story)
  end


private

	def comment_params
		params.require(:comment) .permit(:body)
	end

	def find_story
      # find the story using the dynamic id in the URL
	  	@story = Story.find(params[:story_id])
	end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	
	before_action :find_story, only: [:show, :edit, :update, :destroy]

	def index
			# @string ="My string of characters"
			# @time =Time .now
			if params[:sort] == "popular"
				@stories = Story.all.order('votes_count DESC')
			elsif params[:sort] == "featured"
				@stories = Story.where(is_featured: true)
			else	
				@stories= Story.all.order('created_at DESC')
			end
	end

	def show
		# refactor the code to be DRY
		# @story = Story.find(params[:id])
	end

	def new
		@story= Story.new
	end

	def create 

		@story = Story.new(story_params)
		
		if @story.save
		
			flash[:success] = "Thank for submitting a story!"
		
		redirect_to root_path
	
		else
	
			flash[:error] = "Oops, something went wrong, please try again…"
			render :new
	
		end
		
	end
	
	def edit
		# refactor the code to be DRY
		# @story = Story.find(params[:id])
	end

	def update
		# refactor the code to be DRY
		# @story = Story.find(params[:id])
		
		if @story.update(story_params)
		
			flash[:success] = "Thank for updating this story!"
			redirect_to story_path(@story)
		
		else
		
			flash[:error] = "Oops, something went wrong, please try and again…"
			render :edit
		
		end
	
	end

	def destroy
		# refactor the code to be DRY
		# @story = Story.find(params[:id])
		
		if @story.present?
		
			flash[:success] = "Successfully destroyed '#{@story.title}'"
			@story.destroy
		
		else 
		
			flash[:error] = "Oops, no story found with id #{params[id]}"
		
		end
		
		redirect_to root_path
	
	end

	private
	def story_params
		params.require(:story).permit(:title, :url, :description)
	end

	def find_story
		@story = Story.find(params[:id])
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		@story = Story.find(params[:story_id])
		@vote = @story.votes.new(story_id: params[:story_id], ip_address: request.ip)
		@vote.save 
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/new.html.erb
<%= simple_form_for [@story, @comment] do |f|%>

	<%= f.input :body %>

	<%= f.button :submit %>

<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>

	<head>

		<meta charset="utf-8">
		<title>Stack</title>
		<%= stylesheet_link_tag		"application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>

	</head>

	<body>

		<header>

      <h1>
        <%= link_to image_tag("stack-logo.png"), root_path %>
      </h1>

      <nav>

        <%= link_to "Top", root_path(sort: :popular) %>
        <%= link_to "Recent", root_path %>
        <%= link_to "Featured", root_path(sort: :featured) %>
        <%= link_to "Submit", new_story_path %>

      </nav>

    </header>

      
    <article>

      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </article>

	</body>

</html>

app/views/stories/_form.html.erb
<%= simple_form_for @story do |f| %>

	<%= f.input :title %>
	<%= f.input :url %>
	<%= f.input :description %>

	<%= f.button :submit %>

<% end %>

app/views/stories/edit.html.erb
<h1>Edit</h1>

<%= render "form" %>

app/views/stories/index.html.erb
<% @stories.each do |story|%>
	
	<div class="story">
		<h2><%= link_to story.title, story_path(story) %></h2>

		<p><%= story.description %></p>

		<ul>
			<li><%= link_to "Upvote", story_votes_path(story), method: :post %></li>
			<li><%= pluralize(story.votes.size, "upvote") %></li>
			<li>
				<%= link_to pluralize(story.comments.size, "comment"), story_path(story) %>
			</li>
			<li>
				<%= time_ago_in_words story.created_at %> ago
			</li>
		</ul>

	</div>

<% end %>

app/views/stories/new.html.erb
<h1>New</h1>

<%= render "form" %>

app/views/stories/show.html.erb
<h2><%= link_to @story.title, @story.url %></h2>


<p><%= @story.description %></p>

<p>This was posted <%= time_ago_in_words @story.created_at %> ago</p>

<div class="actions">

	<%= link_to "Edit", edit_story_path(@story) %>
	<%= link_to "Delete", story_path(@story), method: :delete %>

</div>

<div class="comments">

	<% @story.comments.each do |comment| %>

		<%= simple_format comment.body %>

		<%= link_to "delete comment", story_comment_path(comment.story_id, comment), method: :delete %> 

	<% end %>

</div>

<%= link_to "Add a comment", new_story_comment_path(@story) %>